version: "3.8"
services:
  web:
    build: ./api-server
    ports:
      - 4000:4000
    environment:
      DB_URL: #URL for Database ???//db/???
  db:
    build: ./mariadb
    ports:
        - 3000:3306
    volumes:
       - sharedVolume:/data/db
volumes:
   sharedVolume: