version: "3.8"
services:
  web:
    build: .
    ports:
      - 4000:4000
    environment:
      DB_URL: #URL for Database ???//db/???
  db:
    image: mariadb:lts
    ports:
        - 3000:3000
    environment:
      MARIADB_ROOT_PASSWORD: db32!Password
    volumes:
       - sharedVolume:/data/db
volumes:
   sharedVolume: